Added dynamodb client functions and tests
inqdocloud/inqdo-tools-public pull request #38
Opened 2023-04-28 12:41 UTC by lottediesveld

2023-05-01 06:06 UTC, BarryBuitelaar commented
@lottediesveld CI / flake8 failed

2023-05-01 11:08 UTC, BarryBuitelaar requested changes
Please look at the comments

2023-05-01 11:08 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
The docstring for "dynamodb_arn" is not present, and it might be more appropriate to rename it to simply "arn" instead of the previously suggested "dynamodb_arn".

2023-05-01 11:08 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            self.dynamodbclient = boto3.client("dynamodb", region_name=self.region_name)
Wrong naming convention

2023-05-01 11:08 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            self.dynamodbclient = boto3.client("dynamodb", region_name=self.region_name)
I recommend using the "Client" from 'inqdo_tools.utils.get_client' so that the ARN can be properly utilized.

2023-05-01 11:08 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +        if self.endpoint_url:
Structure of if/else statement is to complicated.. 
Revert it and just introduce a if statement for the arn to use the Client

2023-05-01 11:08 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            else:
Else is not necessary

2023-05-01 11:08 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +        else:
Else is not necessary

2023-05-01 11:08 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +                    items.append({k: self.deserializer.deserialize(v) for k, v in item.items()})
DRY .. Make a static method in class

2023-05-01 11:08 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +        :param expression_attribute_names: Expexts one or more substitution tokens for attribute names in an expression.
typo in Expexts

2023-05-01 11:08 UTC, BarryBuitelaar commented on tests/mocks/dynamodb.py
> +def dynamodb_client(aws_credentials):
It may be more convenient to move this code to the top of the file, next to the dynamodb_resource declaration.

2023-05-04 08:24 UTC, BarryBuitelaar reviewed
Paar kleine dingetjes

2023-05-04 08:24 UTC, BarryBuitelaar commented on .vscode/settings.json
> +    "python.analysis.extraPaths": [
Please revert this

2023-05-04 08:24 UTC, BarryBuitelaar commented on .gitignore
> +pyrightconfig.json
Is this necessary?

2023-05-04 08:24 UTC, BarryBuitelaar commented on .gitignore
> +
whitespace

2023-05-04 08:24 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +                return self._deserialize(response)
To make it more readable please insert a blank space

2023-05-04 08:24 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            return self._deserialize(response)
To make it more readable please insert a blank space

2023-05-04 08:24 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +        return self._deserialize(response)
To make it more readable please insert a blank space

2023-05-04 08:24 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +        return self._deserialize(response)
To make it more readable please insert a blank space

2023-05-04 08:24 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            return items
To make it more readable please insert a blank space

2023-05-04 08:24 UTC, BarryBuitelaar commented on tests/unit/dynamodb/test_client_dynamodb.py
> +# # QUERY CLIENT WITH MISSING KEYS
Extra #  found ;)

2023-05-04 09:31 UTC, BarryBuitelaar reviewed
Not resolved

2023-05-04 09:31 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            return items
This is not resolved

2023-05-08 07:05 UTC, BarryBuitelaar reviewed
Remove double methods .. combine logic with existing methods

2023-05-08 07:05 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +    def get_item(self, key: dict):
Remove this method and combine this with method: read

2023-05-08 07:05 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +    def put_item(self, item: dict):
Remove this method and combine this with method: create_and_update

2023-05-08 07:05 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +    def delete_item(self, key: dict):
Remove this method and combine this with method: delete

2023-05-08 07:05 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +    def update_item(
Remove this method and combine this with method: update

2023-05-08 10:13 UTC, BarryBuitelaar reviewed
Please be more precise ..

2023-05-08 10:13 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            return self._deserialize(response)
Entertje ;)

2023-05-08 10:13 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            self.dynamodb_client.put_item(
Do we want to insert the item twice? ..
If Else :)

2023-05-08 10:13 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            response = self.dynamodb_client.update_item(
Do we want to update the item twice? ..
If Else :)

2023-05-08 10:13 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            response = self.dynamodb_client.get_item(
Do we want to get the item twice? ..
If Else :)

2023-05-08 10:13 UTC, BarryBuitelaar commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            self.dynamodb_client.delete_item(
Do we want to delete the item twice? ..
If Else :)

** ALSO.
How did the test ran?
I can imagine that this is not working because first you delete the item on rule 266 and then also on 271 .. you cannot delete files which are not existing anymore? Although, maybe boto3 does not covers this..

Anyway, calling the delete item twice is not how it should work

2023-05-08 11:04 UTC, lottediesveld commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            self.dynamodb_client.put_item(
I changed the order so an else statement isn't needed, but the item is not inserted twice

2023-05-08 11:04 UTC, lottediesveld commented on inqdo_tools/src/inqdo_tools/dynamodb/client.py
> +            self.dynamodb_client.delete_item(
The test ran successfully, I changed the code to if/else

2023-05-15 07:11 UTC, merged